lm32: Fix module relocation warnings
We have implmentations for these functions, but we needed to tell Kbuild about
them.

arch/lm32/kernel/module.c:100:5: error: redefinition of ‘apply_relocate’
 int apply_relocate(Elf32_Shdr *sechdrs, const char *strtab,
     ^
In file included from arch/lm32/kernel/module.c:1:0:
./include/linux/moduleloader.h:42:19: note: previous definition of ‘apply_relocate’ was here
 static inline int apply_relocate(Elf_Shdr *sechdrs,
                   ^
arch/lm32/kernel/module.c:106:5: error: redefinition of ‘apply_relocate_add’
 int apply_relocate_add(Elf32_Shdr *sechdrs, const char *strtab,
     ^
In file included from arch/lm32/kernel/module.c:1:0:
./include/linux/moduleloader.h:65:19: note: previous definition of ‘apply_relocate_add’ was here
 static inline int apply_relocate_add(Elf_Shdr *sechdrs,
                   ^

Signed-off-by: Joel Stanley <joel@jms.id.au>