lm32: asm: remove empty exit_thread
It was causing a build error, and wasn't doing anything for us. I assume we
fall back on a generic implementation.

 In file included from arch/lm32/kernel/asm-offsets.c:15:0:
 ./include/linux/sched.h:2881:20: error: conflicting types for ‘exit_thread’
  static inline void exit_thread(struct task_struct *tsk)
                     ^
 In file included from ./include/linux/spinlock_up.h:8:0,
                  from ./include/linux/spinlock.h:89,
                  from ./include/linux/seqlock.h:35,
                  from ./include/linux/time.h:5,
                  from ./include/uapi/linux/timex.h:56,
                  from ./include/linux/timex.h:56,
                  from ./include/linux/sched.h:19,
                  from arch/lm32/kernel/asm-offsets.c:15:
 ./arch/lm32/include/asm/processor.h:103:20: note: previous definition of ‘exit_thread’ was here
  static inline void exit_thread(void)
                     ^
Signed-off-by: Joel Stanley <joel@jms.id.au>