lm32: signal: fix missing sig_rt_sigreturn
arch/lm32/built-in.o:(.data+0x2c0): undefined reference to
`sys_rt_sigreturn'

Signed-off-by: Joel Stanley <joel@jms.id.au>